services:
  # Backend API Service
  - type: web
    name: smart-study-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: groq
      - key: DEFAULT_MODEL
        value: llama3-8b-8192
      - key: MAX_TOKENS
        value: "1024"
      - key: TEMPERATURE
        value: "0.7"
      - key: MONGO_URI
         sync: false  # Or use 'value' if you want to hardcode a test DB URI (not recommended)


  # Frontend "Static" Site treated as web with static env
  - type: web
    name: smart-study-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    startCommand: echo "This is a static site."
    envVars:
      - key: REACT_APP_API_URL
        value: https://smart-study-backend.onrender.com
