services:
  # Backend API Service
  - type: web
    name: smart-study-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add your environment variables here
      - key: GROQ_API_KEY
        sync: false  # This will be set manually in Render dashboard
      - key: LLM_PROVIDER
        value: groq
      - key: DEFAULT_MODEL
        value: llama3-8b-8192
      - key: MAX_TOKENS
        value: "1024"
      - key: TEMPERATURE
        value: "0.7"

  # Frontend Static Site
  - type: web
    name: smart-study-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://smart-study-backend.onrender.com  # Update this with your backend URL